### ISSUE TITLE
Log to syslog

### ISSUE THREAD

**Issue by NickeZ** [ralphlange/procServ#13]
Hi,

Is it possible to log to syslog or use an external application for logging (like [logger](https://linux.die.net/man/1/logger))?

My plan is to not fill up my hard drives with output from the IOC when the IOC is misbehaving.

**Comment by ralphlange** [comment]
If you use the -l / --logport option, any application can connect (from anywhere) to the specified TCP port and gets a copy of the complete console output.

**Comment by NickeZ** [comment]
OK. Thank you for your time. Unfortunately that doesn't solve my issue since I want the IOC to drive the logging.

**Comment by ralphlange** [comment]
The IOC always drives the logging. The only difference is who is opening
the TCP connection.

**Comment by NickeZ** [comment]
Yeah, but I was looking at simply using a syslogd server listening on udp 514. Which would be zero configuration.

**Comment by ralphlange** [comment]
Wouldn't something along the lines of
``( nc 127.0.0.1 12345 | logger ) & procServ -l 12345``
do?
All you need is something that listens on the logport and writes to syslog.
You can move the ( nc | logger ) to some server machine if starting it with the IOC sounds like too much trouble.

Or skip procServ logging and use something more powerful like conserver (http://conserver.com/) to do logging, timestamping, access control, reopening connections, name-to-host/port translation etc etc.
In production, I never ran procServ without conserver. I would actually drop the logging part from procServ completely (for simplification) if I didn't know a lot of users rely on it.

**Comment by ralphlange** [comment]
I do see your zero configuration point, though.

**Comment by NickeZ** [comment]
Hmm. I could probably use the -f / --foreground flag and configure journald to send all the processes output over the network since I'm running procServ as a systemd service.

**Comment by ralphlange** [comment]
Sounds feasible.

Please also have a look at https://github.com/ralphlange/procServ/pull/11
which is on my list for review and merging.

**Comment by NickeZ** [comment]
It didn't work. I'm guessing that since stdin is connected to /dev/null procServ will read EOF and then don't output anything..

If I on the other hand use -d / --debug it works as expected. Are there any drawbacks to always run procServ in debug mode?

**Comment by ralphlange** [comment]
Look at Michael's pull request. This might be why he added a new command line option.

There are no real drawbacks of debug mode that I can think of. You might get more log output.

**Comment by NickeZ** [comment]
Yeah, I made some comments in the pull request, for now I can use the workaround I have with debug mode.

**Comment by ralphlange** [comment]
Glad you have something working.
