### ISSUE TITLE
Support logging to Syslog

### ISSUE THREAD

**Issue by kasemir** [ralphlange/procServ#25]
Logging is one of the big advantages of using procServ.
The `--logfile` option writes to a file.
On Linux systems, it would be nice to also support writing to the system logs (/var/log/messages etc.) instead of to a file.

Was brought up in https://github.com/shroffk/phoebus/issues/612.

Seems similar to #13

**Comment by ralphlange** [comment]
Setting `-L -` should send the log to stdout.
In combination with a system daemon manager (like systemd/supervisord) and foreground mode, doesn't that allow you to send the log output to syslog through the system daemon logging?
