### ISSUE TITLE
Not building with python3

### ISSUE THREAD

**Issue by ffeldbauer** [ralphlange/procServ#30]
Hey Ralph,

I wanted to test the new procServ release on Debian Buster with Python 3.7.3 from the standard debian repo and found the following problem if I build procServ with
```
PYTHON=/usr/bin/python3 ./configure --with-systemd-utils
make
[...]
(cd .; /usr/bin/python3 setup.py build \
--build-base /home/florian/foo/procServ-2.8.0/build)
  File "setup.py", line 17
    os.chmod(file, 0755)
                      ^
SyntaxError: invalid token
make: *** [Makefile:999: all-local] Error 1
```
For python3.7 octal numbers have to be formatted as `0o755`. I tested this change with python3.7 and python2.7, works for both

**Comment by ralphlange** [comment]
Yep. That's correct.
