### ISSUE TITLE
core dump size limitation?

### ISSUE THREAD

**Issue by chrisvam** [ralphlange/procServ#36]
Hi,

We're using an older version of procServ, but we've encountered an issue we think may still be there in a new version.  This line sets a variable "k" that is used to store a coreSize, but is an int which we think is 32-bits on our rhel7 system:

https://github.com/ralphlange/procServ/blob/e2b20acea63652c085456dde8d4471cf508e8b4b/procServ.cc#L209

It appears that as a result we can't get core dumps that are larger than 2GB: larger core files are truncated and hence unusable.

Thanks for any thoughts you might have on this...

chris

**Comment by ralphlange** [comment]
Your observation is true - I will fix this in the next version. Thanks for pointing this out.

However, this variable is only used when you specify a core limit size using the `--coresize` command line option.
Without this option, variable `k` does not get used and the core limit is inherited. Are you sure that the core size is not restricted on a system level or for the user? What does `ulimit -c` say?

**Comment by chrisvam** [comment]
On Jul 1, 2020, at 3:28 AM, Ralph Lange <notifications@github.com<mailto:notifications@github.com>> wrote:


However, this variable is only used when you specify a core limit size using the --coresize command line option.
Without this option, variable k does not get used and the core limit is inherited. Are you sure that the core size is not restricted on a system level or for the user? What does ulimit -c say?


Hi Ralph,

Yes, agreed that the inherited ulimit is a good workaround:  we are doing that.  Thanks for your work on procServ ... we’ve been using it for years at this large LCLS facility at SLAC ... extremely useful!

chris

**Comment by ralphlange** [comment]
:blush: Thank you!
