### ISSUE TITLE
Add procServ to EPEL 9

### ISSUE THREAD

**Issue by gohierf** [ralphlange/procServ#55]
We used to install procServ easily on CentOS 7, using the EPEL repositories.

But for Rocky 9 we found that is it not available this way.

[repology.org shows that the package is not on EPEL 9.](https://repology.org/project/procserv/versions)

Could you add procServ to EPEL 9 ?

**Comment by ralphlange** [comment]
Noted.

That is, however, a process that for formal reasons takes a few weeks. Please compile locally or build your own Rocky 9 RPM as a workaround.

**Comment by leblancOUAL** [comment]
I submitted a bug report at https://bugzilla.redhat.com/show_bug.cgi?id=2231918

The EPEL folks also ran a test build for me, so packages are available as long as this page exists:
https://koji.fedoraproject.org/koji/taskinfo?taskID=104837191

I've downloaded but not tested this package yet.

**Comment by ralphlange** [comment]
Fedora Update System 2023-09-10 00:35:48 UTC
FEDORA-EPEL-2023-07703982b5 has been pushed to the Fedora EPEL 9 stable repository.
