### ISSUE TITLE
Makefile.Epics should define PROD_CMD too

### ISSUE THREAD

**Issue by dirk-zimoch** [ralphlange/procServ#56]
https://github.com/ralphlange/procServ/blob/cd68a34da12ec156c4126932b62947ee195b6210/Makefile.Epics.in#L12
In EPICS R7.0.5, a new `VALID_BUILDS` choice `Command` has been introduced for architectures that need command line tools but not all the build tools like antelope. Thus, some Architectures may now use `Command` but no longer `Host` in their `VALID_BUILDS`. On those architectures, procServ is erroneously not built because  procServ uses `PROC_HOST` only.

Specifying both, `PROC_HOST = procServ`  ___and___ `PROC_CMD = procServ` ensures that proServ is built for all architectures, that use the old `Host` ___or___ the new `Command` in their `VALID_BUILDS`.

**Comment by ralphlange** [comment]
Sounds reasonable.

**Comment by dirk-zimoch** [comment]
Fixed the quite consistent typo: I wrote PROC instead of PROD.

**Comment by ralphlange** [comment]
Don't worry. The commit was valid. 😉
